version: '3'

services:

  emildorado:
    container_name: emildorado
    restart: always
    build:
      context: ./emildorado
    hostname: emildorado
    ports:
      - 20000:20000
    networks:
      - backend

  db-emildorado:
    container_name: emildorado
    restart: always
    image: postgres:12.2-alpine
    hostname: emildorado
    volumes:
      - db-emildorado:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=emildorado
      - POSTGRES_PASSWORD=emildorado
      - POSTGRES_DB=emildorado
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-emildorado:
